# Site settings
title: Michael Chungyoun
author:
  name: Michael Chungyun
  email: mchungy1@jhu.edu
description: "<i class='fab fa-github'></i> [GitHub](https://github.com/MichaelChungyoun)<br> <i class='fab fa-twitter'></i> [Twitter](https://twitter.com/MikeyChungyoun)."

# Build settings
remote_theme: jekyll/minima
