# Site settings
title: Michael Chungyoun
author:
  name: Michael Chungyun
  email: mchungy1@jhu.edu
description: "Link to [GitHub](https://github.com/MichaelChungyoun). <br> Link to [Twitter](https://twitter.com/MikeyChungyoun)."

# Build settings
remote_theme: jekyll/minima
