# Site settings
title: Michael Chungyoun 🇫🇷 🇲🇺
author:
  name: Michael Chungyun
  email: mchungy1@jhu.edu
description: "GitHub](https://github.com/MichaelChungyoun). [Twitter](https://twitter.com/MikeyChungyoun)."

# Build settings
remote_theme: jekyll/minima
