# Site settings
title: Michael Chungyoun 🇫🇷 🇲🇺
author:
  name: Michael Chungyoun
  email: mchungy1@jhu.edu
  twitter_username: MikeyChungyoun
  github_username: MichaelChungyoun

# Build settings
remote_theme: jekyll/minima
